site_name: Processor CI
site_author: Julio Avelar, Rodolfo Azevedo, Victor Lago, Angelo Malaguti, Gabriel Gomes
site_description: The Processor CI is an open-source framework that provides a set of tools to facilitate the verification of processors in a continuous integration environment with the assistance of FPGAs.
site_url: https://processorci.ic.unicamp.br
repo_name: processor-ci-website
repo_url: https://github.com/LSC-Unicamp/processor-ci-website
copyright: CC BY-SA 4.0
theme: 
  name: material
  highlightjs: true
  logo: assets/logo.svg
  favicon: assets/logo.svg
  #language: en
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - tables
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LSC-Unicamp
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
      lang:
        - en
        - pt
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
        - locale: pt
          name: Português

nav:
  - Home : index.md
  - Cores: cores.md
  - Hardware infrastructure: hardware_infrastructure.md
  - Software Tests: software_tests.md
  - Contributing: contributing.md
  - About : about.md